---
- name: Provisioning MySQL Server for WordPress
  hosts: all	
  tasks:
    - name: Including default vars file
      ansible.builtin.include_vars: ../defaults/vars.yml

    - name: Installing mysql-server
      ansible.builtin.apt:
        name: mysql-server
        state: present
        update_cache: yes
      become: yes

    - name: Making sure python3-pip is present
      ansible.builtin.apt:
        name: python3-pip
        state: present
      become: yes

    - name: Installing PyMySQL Python module
      ansible.builtin.pip:
        name:
          - setuptools
          - PyMySQL
      become: yes     

    - name: Creating '{{ wp_mysql_db_name }}' MySQL database
      community.mysql.mysql_db:
        name: '{{ wp_mysql_db_name }}'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes

    - name: Creating '{{ wp_mysql_user }}' MySQL user and granting database privileges 
      community.mysql.mysql_user:
        name: '{{ wp_mysql_user }}'
        # password
        password: wordpresspw
        priv: 'wordpress.*:ALL'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes

    - name: Updating bind-address in mysqld.cnf to allow remote connections on private network interface
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 192.168.56.15'
        owner: root
        group: root
        mode: '0644'       
      become: yes

    # remove this   
    - name: Granting access to 'wordpress' MySQL database from 192.168.56.10
      community.mysql.mysql_query:
        query: 
        - GRANT ALL ON wordpress.* TO wordpress@'192.168.56.10' IDENTIFIED BY 'wordpresspw'
        - GRANT ALL ON wordpress.* TO wordpress@'192.168.56.11' IDENTIFIED BY 'wordpresspw'
        login_unix_socket: /run/mysqld/mysqld.sock
      become: yes 

    # handler
    - name: Restarting MySQL server
      ansible.builtin.service:
        name: mysql
        state: restarted
      become: yes
