---
- name: Deploy Nginx Load Balancer
  hosts: all
  tasks: 
    # Not DRY
    - name: Installing Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: yes

    - name: Configuring Nginx Load Balancer
      ansible.builtin.template:
        src: nginx_lb.j2
        # Variable (lb)
        dest: /etc/nginx/sites-available/lb
        owner: root
        group: root
        mode: '0644'
      become: yes

    # Not DRY
    # Variable (lb)
    - name: Creating symlink from sites-available/lb to sites/enabled/default
      file:
        # variable (lb)
        src: /etc/nginx/sites-available/lb
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes

    # Not DRY
    - name: Restarting Nginx
      service: 
        name: nginx
        state: restarted
      become: yes
