---
- name: Deploy WordPress main node
  hosts: all
  tasks:
    - name: Updating Apt cache and making sure Apache is absent
      ansible.builtin.apt:
        name: apache2
        state: absent
        update_cache: yes
      become: yes

    - name: Installing PHP modules
      ansible.builtin.apt:
        pkg:
        - php-mysql
        - php-curl
        - php-gd
        - php-intl
        - php-mbstring
        - php-soap
        - php-xml
        - php-xmlrpc
        - php-zip
        - php-fpm
        state: present
      become: yes

    - name: Installing Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      become: yes      

    - name: Dowloading and Extracting latest Wordpress to /var/www/wordpress
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz    
        dest: /var/www/
        remote_src: yes
      become: yes

#    - name: Changing ownership of /var/www/wordpress to www-data
        # ?
      
    - name: Configuring wp-config.php
      ansible.builtin.template:
        src: wp-config.php.j2
        dest: /var/www/wordpress/wp-config.php
        owner: www-data
        group: www-data
      become: yes

    - name: Adding nginx configuration for wordpress site to sites-available
      ansible.builtin.template:
        src: nginx_conf_wordpress.j2
        dest: /etc/nginx/sites-available/wordpress
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Creating symlink from sites-available/wordpress to sites-enabled/default
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes

    - name: Restarting Nginx
      service:
        name: nginx
        state: restarted
      become: yes
